name: Run VSCode Extension Tests

on:
  push:
env:
  DISPLAY: ":1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v4
        name: Cache node modules
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Cache vscode-test
        uses: actions/cache@v4
        with:
          path: .vscode-test
          key: ${{ runner.os }}-vscode-test
          restore-keys: |
            ${{ runner.os }}-vscode-test

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile:test

      - name: Run tests
        run: npm run test
